<?php
$field_id	 = $this->field['field_id'];
$field_title     = $this->field['title'];
$required	 = $this->field['required'];
$field_class     = $this->field['field_class'];
$field_note	 = $this->field['field_note'];
$tooltip	 = $this->field['tooltip'];
if($required){
    $custom_message = $this->field['custom_validation'];
    $custom_class = ' required-entry-'.$this->field['field_id'];
    $required_class = (!empty($custom_message)) ? $custom_class : ' required-entry';
}
else
{
    $required_class='';
}
//To retrive field value on unsuccess submission
$field_value = Mage::helper('flexibleforms');
if($this->field['type']=='star'):
    $max_value = ($this->field['form_star_max_value']) ? $this->field['form_star_max_value'] : 5;
    $default_value = ($this->field['form_star_default_value']) ? $this->field['form_star_default_value'] : 0;
    
    ?>
    <label <?php echo $required ? ' class="required" ' : '' ?> ><?php echo $this->__($field_title); ?> <?php echo $required ? ' <em>*</em> ' : '' ?></label>
    <?php if($tooltip): ?>
        <span id="label-info">
            <img src="<?php echo $this->getSkinUrl("css/flexibleforms/images/help.png"); ?>" alt="<?php echo $this->__('Help'); ?>" />
            <span class="label-info-tooltip"><?php echo $tooltip; ?></span>
        </span>
    <?php endif; ?>
    <div class="input-box">
        <div id="starfield<?php echo $field_id; ?>"></div>
        <input type="hidden" id="options_<?php echo $field_id; ?>" name="options[<?php echo $field_id; ?>]" value="<?php echo $field_value->getFieldValue($default_value);?>" class="<?php echo $required_class ? $required_class : '' ?>" />
	<?php if($field_note): ?>
            <p class="note"><?php echo $field_note; ?></p>
        <?php endif; ?>
    </div>
<?php endif; ?>
<script type="text/javascript">
    //<![CDATA[
    (function( $ ) {
        $("#starfield<?php echo $field_id; ?>").rateYo({
            numStars: <?php echo $max_value;?>,
            maxValue: <?php echo $max_value;?>,
            rating: <?php echo $default_value;?>,
            fullStar: true,
            onSet: function (rating, rateYoInstance) {
               $('#options_<?php echo $field_id; ?>').val(rating);
            }
        });
    })( ffm );
    //]]>
</script>