<?php
/**
 * @package SmartAddons
 * @category SM Block Tabs
 * @copyright (c) 2009-2012 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author YouTech Company http://www.smartaddons.com
 */

$instance	= rand().time();
$tabs = $this->getChild();
if ( count($tabs) ){
	$tab_selected = $this->tab_selected <= count($tabs)? $this->tab_selected : 1;
	$tab_selected = $content_selected = $tab_selected > 0 ? $tab_selected : 1;
	
	$jsHelper = Mage::helper('core/js');
	$jquery = $jsHelper->includeSkinScript('smartaddons/blocktabs/js/jquery-1.5.min.js');
	$jsmart = $jsHelper->includeSkinScript('smartaddons/blocktabs/js/jsmart.noconflict.js');
	$jsease = $jsHelper->includeSkinScript('smartaddons/blocktabs/js/jsmart.easing.1.3.js');
	$jstabs = $jsHelper->includeSkinScript('smartaddons/blocktabs/js/jsmart.tabs.js');
	if (null == Mage::registry('jsmart.jquery')){
		// jquery has not added yet
		if ( $this->include_jquery ){
			// if module allowed jquery.
			echo $jquery;
			Mage::register('jsmart.jquery', 1);
		}
	}
	echo $jsmart.$jsease.$jstabs;
?>
<script type="text/javascript">
	$jsmart(document).ready(function($){
		$('.blocktabs').each(function(){
			var $this = $(this), $istabs = $this.data('tabs');
			if ( !$istabs ){
				$this.tabs();
				$this.data('tabs', 1);
			}
		});
	});
</script>
<div class="blocktabs top-position">
	<div class="tabs-container font1">
		<ul class="tabs">
			<?php $i = 0; ?>
			<?php foreach($tabs as $name => $block): ?>
			<?php 
				//$arr_word =  $block->block_title ? explode(' ',$block->block_title) : explode(' ',$this->__($name));
				//$join_word = array_shift($arr_word).' <span>'.implode(' ',$arr_word).'</span>';
			?>
			<li<?php if (++$i==$tab_selected) echo ' class="sel"'; ?>><div class="tab"><h3><?php echo  $block->block_title;//echo $join_word; ?></h3></div></li>
			<?php endforeach; ?>
		</ul>
	</div>
	<div class="tabs-content">
		<div class="tabs-content-inner">
			<?php $i = 0; ?>
			<?php foreach($tabs as $name => $block): ?>
			<div class="tab-content<?php if (++$i==$content_selected) echo ' sel'; ?>">
				<?php echo $this->getChildHtml($name); ?>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
	<div class="slider-control">
		<ul>
			<li class="prev disabled">Prev</li>
			<li class="next">Next</li>
		</ul>
	</div>
</div>
<?php } ?>